// timeline.js — single source of truth for the edit: scene windows, script lines, and audio cues.
// 120 BPM → 1 beat = 0.5 s = 15 frames @ 30 fps. 1 bar = 2 s.
// Loaded by the browser (window.TL) and by Node (module.exports) for the audio build.
(function (root) {
  const S = {
    hook: [0, 4],
    promise: [4, 8],
    read: [8, 12],
    tokens: [12, 16],
    embed: [16, 24],
    attn: [24, 32],
    layers: [32, 36],
    predict: [36, 44],
    loop: [44, 48],
    train: [48, 52],
    latest: [52, 56],
    finale: [56, 64],
  };

  // Script (Maltese) with English glosses — also exported as subtitles / storyboard
  const SCRIPT = [
    [0.0, 'DAN IL-FILMAT', 'This video'],
    [0.5, 'GĦAMILTU', 'I made it'],
    [1.0, 'JIEN.', 'myself.'],
    [1.5, 'L-AI.', 'The AI.'],
    [1.6, '(iva, veru)', '(yes, really)'],
    [2.0, 'KULL PIXEL.', 'Every pixel.'],
    [2.5, 'KULL NOTA.', 'Every note.'],
    [3.0, 'KULL KELMA.', 'Every word.'],
    [3.5, 'BIL-MALTI.', 'In Maltese.'],
    [4.0, 'Issa ħa nurik', 'Now I’ll show you'],
    [4.75, 'KIF NAĦDEM', 'how I work'],
    [5.75, "f'60 sekonda.", 'in 60 seconds.'],
    [8.0, "L-EWWEL: QRAJT.", 'First: I read.'],
    [10.0, "TRILJUNI TA' KLIEM.", 'Trillions of words.'],
    [11.0, "aktar milli taqra f'elf ħajja.", 'more than you’d read in a thousand lifetimes.'],
    [12.0, 'IMMA MA NARAX KLIEM.', 'But I don’t see words.'],
    [12.75, 'NARA TOKENS.', 'I see tokens.'],
    [15.0, 'Kull biċċa ssir numru.', 'Every piece becomes a number.'],
    [15.25, "Bil-Malti, il-kliem jinqasam f'aktar biċċiet.", 'In Maltese, words split into more pieces.'],
    [16.0, 'MAPPA TAT-TIFSIRA', 'A map of meaning'],
    [16.5, 'Kull token isir punt.', 'Every token becomes a point.'],
    [18.0, 'Kelmiet simili jgħixu qrib xulxin.', 'Similar words live near each other.'],
    [20.0, 'RE − RAĠEL + MARA ≈ REĠINA', 'KING − MAN + WOMAN ≈ QUEEN'],
    [22.5, "…f'eluf ta' dimensjonijiet.", '…in thousands of dimensions.'],
    [24.75, 'IMBAGĦAD: ATTENZJONI.', 'Then: attention.'],
    [25.5, "Kull kelma tħares lejn l-oħrajn.", 'Every word looks at the others.'],
    [26.0, 'Poġġejt il-flus fil-bank.', 'I put the money in the bank.'],
    [28.0, 'Qgħadt fuq il-bank fil-ġnien.', 'I sat on the bench in the garden.'],
    [30.0, 'IL-KUNTEST JIBDEL KOLLOX.', 'Context changes everything.'],
    [32.0, 'U DAN JIĠRI…', 'And this happens…'],
    [33.25, "GĦEXIEREN TA' DRABI.", 'dozens of times.'],
    [34.25, "B'BILJUNI TA' PARAMETRI.", 'with billions of parameters.'],
    [36.0, 'U FL-AĦĦAR?', 'And in the end?'],
    [36.75, 'INBASSAR IL-KELMA LI JMISS.', 'I predict the next word.'],
    [38.0, 'L-aħjar pastizzi huma tal-…', 'The best pastizzi are the…'],
    [41.0, "Lanqas jien ma nista' niddeċiedi.", 'Not even I can decide.'],
    [42.0, "It-traffiku f'Malta huwa…", 'Traffic in Malta is…'],
    [44.0, 'NAGĦŻEL WAĦDA.', 'I pick one.'],
    [44.75, 'INŻIDHA.', 'I add it.'],
    [45.5, "U NERĠA' NIBDA.", 'And start again.'],
    [46.0, "Bonġu! Kif nista' ngħinek illum?", 'Hello! How can I help you today?'],
    [47.5, "KELMA B'KELMA.", 'Word by word.'],
    [48.0, 'KIF TGĦALLIMT?', 'How did I learn?'],
    [48.75, 'Bassart.', 'I guessed.'],
    [49.25, 'Żbaljajt.', 'I got it wrong.'],
    [49.75, 'Irranġajt.', 'I adjusted.'],
    [51.25, "TRILJUNI TA' DRABI.", 'Trillions of times.'],
    [52.0, 'U ILLUM?', 'And today?'],
    [52.5, 'L-aqwa mudelli jaħsbu pass pass qabel iwieġbu.', 'The best models think step by step before answering.'],
    [54.0, 'U jużaw l-għodod.', 'And they use tools.'],
    [55.0, "…anke biex jagħmlu filmati bħal dan.", '…even to make videos like this one.'],
    [56.0, 'MHUX MAĠIJA.', 'Not magic.'],
    [57.0, 'MATEMATIKA.', 'Maths.'],
    [59.0, 'Irkotta jew piżelli?', 'Ricotta or peas?'],
    [59.5, 'ikteb fil-kummenti', 'write in the comments'],
    [61.0, 'Segwi għal aktar AI bil-Malti', 'Follow for more AI in Maltese'],
  ];

  // Audio cues (sound design) — [time, type, params]
  const CUES = [
    // hook
    [0.0, 'impact', { size: 1.0 }],
    [0.5, 'hit', { note: 50 }],
    [1.0, 'hit', { note: 53 }],
    [1.5, 'glitch', { dur: 0.3 }],
    [1.5, 'drop', {}],
    [2.0, 'stab', { note: 62 }],
    [2.5, 'stab', { note: 65 }],
    [3.0, 'stab', { note: 69 }],
    [3.5, 'stab', { note: 74, big: 1 }],
    // promise
    [4.0, 'type', { n: 13, dur: 0.6 }],
    [4.75, 'hit', { note: 50, soft: 1 }],
    [5.0, 'hit', { note: 53, soft: 1 }],
    [5.75, 'pop', { note: 81 }],
    [6.5, 'whoosh', { dur: 0.5 }],
    [7.0, 'implode', { dur: 0.75 }],
    [7.5, 'reverse', { dur: 0.5 }],
    // read
    [8.0, 'impact', { size: 1.0 }],
    [8.6, 'stream', { dur: 2.2 }],
    [10.0, 'hit', { note: 50 }],
    [11.0, 'shimmer', { dur: 0.8 }],
    [11.5, 'whoosh', { dur: 0.5, up: 1 }],
    // tokens
    [12.0, 'hit', { note: 53 }],
    [12.75, 'hit', { note: 57 }],
    [13.2, 'zap', {}],
    [13.35, 'zap', {}],
    [13.5, 'zap', {}],
    [13.65, 'zap', {}],
    [13.8, 'pop', { note: 72 }],
    [13.88, 'pop', { note: 76 }],
    [13.96, 'pop', { note: 79 }],
    [14.04, 'pop', { note: 83 }],
    [14.12, 'pop', { note: 84 }],
    [14.3, 'flip', {}],
    [14.4, 'roll', { note: 84 }],
    [14.48, 'roll', { note: 86 }],
    [14.56, 'roll', { note: 88 }],
    [14.64, 'roll', { note: 89 }],
    [14.72, 'roll', { note: 91 }],
    [15.0, 'blip', { note: 88 }],
    [15.5, 'whoosh', { dur: 0.5 }],
    // embed
    [16.0, 'impact', { size: 0.7 }],
    [16.5, 'shimmer', { dur: 1.5 }],
    [18.0, 'blip', { note: 84 }],
    [20.0, 'blip', { note: 76 }],
    [20.5, 'swoop', { dur: 0.6 }],
    [21.3, 'swoop', { dur: 0.6 }],
    [22.0, 'hit', { note: 57 }],
    [22.5, 'whoosh', { dur: 1.0, up: 1 }],
    [23.5, 'reverse', { dur: 0.5 }],
    // attention (breakdown)
    [24.0, 'eye', {}],
    [24.75, 'hit', { note: 50, soft: 1 }],
    [26.2, 'pluck', { note: 69 }],
    [26.35, 'pluck', { note: 72 }],
    [26.5, 'pluck', { note: 76 }],
    [26.65, 'pluck', { note: 81 }],
    [27.2, 'pop', { note: 74 }],
    [28.2, 'pluck', { note: 67 }],
    [28.35, 'pluck', { note: 71 }],
    [28.5, 'pluck', { note: 74 }],
    [28.65, 'pluck', { note: 79 }],
    [29.2, 'pop', { note: 71 }],
    [30.0, 'hit', { note: 50 }],
    [31.25, 'whoosh', { dur: 0.75, up: 1 }],
    // layers (build)
    [32.0, 'impact', { size: 0.6 }],
    [32.0, 'riser', { dur: 4.0 }],
    [33.25, 'hit', { note: 55, soft: 1 }],
    [34.25, 'hit', { note: 57, soft: 1 }],
    [35.5, 'implode', { dur: 0.5 }],
    // predict (drop 2)
    [36.0, 'impact', { size: 1.0 }],
    [36.75, 'hit', { note: 62 }],
    [38.0, 'type', { n: 26, dur: 0.8 }],
    [38.9, 'race', { dur: 1.6 }],
    [40.5, 'ding', {}],
    [41.0, 'tapestop', {}],
    [42.0, 'type', { n: 22, dur: 0.55 }],
    [42.6, 'horn', {}],
    [43.5, 'whoosh', { dur: 0.5 }],
    // loop
    [44.0, 'hit', { note: 50 }],
    [44.75, 'hit', { note: 53 }],
    [45.5, 'hit', { note: 57 }],
    [46.00, 'tok', { note: 72 }],
    [46.30, 'tok', { note: 74 }],
    [46.55, 'tok', { note: 76 }],
    [46.76, 'tok', { note: 78 }],
    [46.93, 'tok', { note: 80 }],
    [47.07, 'tok', { note: 82 }],
    [47.19, 'tok', { note: 84 }],
    [47.29, 'tok', { note: 86 }],
    [47.38, 'tok', { note: 88 }],
    [47.46, 'tok', { note: 90 }],
    [47.5, 'stab', { note: 74 }],
    // train
    [48.0, 'impact', { size: 0.6 }],
    [48.75, 'blip', { note: 79 }],
    [49.25, 'buzz', {}],
    [49.75, 'ding', {}],
    [50.0, 'montage', { dur: 1.25 }],
    [51.25, 'hit', { note: 62 }],
    // latest
    [52.0, 'hit', { note: 50, soft: 1 }],
    [52.5, 'shimmer', { dur: 1.4 }],
    [54.0, 'pop', { note: 72 }],
    [54.15, 'pop', { note: 76 }],
    [54.3, 'pop', { note: 79 }],
    [54.45, 'pop', { note: 84 }],
    [55.0, 'riser', { dur: 1.0 }],
    [55.6, 'reverse', { dur: 0.4 }],
    // finale
    [56.0, 'heartbeat', {}],
    [57.0, 'impact', { size: 1.4 }],
    [57.05, 'fireworks', { dur: 2.0 }],
    [59.0, 'hit', { note: 62 }],
    [59.5, 'pop', { note: 79 }],
    [61.0, 'hit', { note: 57 }],
    [62.75, 'glitch', { dur: 0.35 }],
    [63.2, 'type', { n: 13, dur: 0.6 }],
  ];

  const TL = { S, SCRIPT, CUES, DURATION: 64, BPM: 120 };
  if (typeof module !== 'undefined' && module.exports) module.exports = TL;
  else root.TL = TL;
})(typeof window !== 'undefined' ? window : globalThis);
